spring:
  cloud:
    gateway:
      routes:
        - id: index12306-user-service
          uri: lb://index12306-user${unique-name:}-service/api/user-service/**
          predicates:
            - Path=/api/user-service/** # 判断请求路径是否符合上述规则
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/user-service/passenger
                  - /api/user-service/query
                  - /api/user-service/logout
                  - /api/user-service/deletion